name: Fluid Attacks Skims
on: [push, pull_request]

jobs:
  skims:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://docker.io/fluidattacks/skims:latest
        name: skimsStandalone
        with:
          args: skims scan . --fail-on HIGH
