# .github/workflows/dev.yml
name: Standalone CLI
on: [push, pull_request]

jobs:
  scan_export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run scan
        uses: docker://docker.io/fluidattacks/skims:latest
        with:
          args: skims scan ./config.yml
          
      - name: Upload CSV Report
        uses: actions/upload-artifact@v4
        with:
          name: fluid-attacks-report
          path: Fluid-Attacks-Results.csv